### ISSUE TITLE
Upload details are not shown

### ISSUE THREAD

**Issue by Excel1** [burgha/nextcloud_uploaddetails#3]
Upload details are not shown. Only the default remaining upload time:

Nextcloud-Version: 16.0.4.1
Browser Cache: cleared
Plugin Version: 0.1.1

**Comment by burgha** [comment]
Could you provide a list of other installed apps ? i cant reproduce it with a clean install of nextcloud

**Comment by Excel1** [comment]
> 
> 
> Could you provide a list of other installed apps ? i cant reproduce it with a clean install of nextcloud

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - announcementcenter: 3.5.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - deck: 0.6.6
  - encryption: 2.4.0
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - fulltextsearch: 1.3.6
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.2
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - passwords: 2019.9.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - unsplash: 1.1.3
  - updatenotification: 1.6.0
  - uploaddetails: 0.1.1
  - user_ldap: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - audioplayer
  - contacts
  - gallery
  - survey_client
  - text

These are my active (and supported) nextcloud apps.

**Comment by burgha** [comment]
thanks, which browser are you using ?

**Comment by Excel1** [comment]
Latest version of firefox (windows)

**Comment by burgha** [comment]
sorry, i just cant reproduce it. is there anything specific about your instance that might help me troubleshoot ?

**Comment by Excel1** [comment]
No sorry. But maybe it can be referenced with the other issue ticket.

**Comment by burgha** [comment]
i just fixed a bug which prevented it from working in internet explorer. could you test if maybe this helps with your firefox too ?

**Comment by Excel1** [comment]
I tried your new version but i still have the problem. Could be the language a problem? (I also looked in the console but i couldnt find any error)

**Comment by burgha** [comment]
it could be, what language are you using ?

**Comment by Excel1** [comment]
German

**Comment by Excel1** [comment]
I only see the time (like the default settings) but no speed (like mb/s)

**Comment by burgha** [comment]
I'm german myself, so this should not be an issue. If you know how to use the browser dev-tools could you inspect the uploadbar like so: [link](https://imgur.com/a/kOCxFnF) and see if the text is there ? the addon takes its data from this source

**Comment by 4L3XK** [comment]
Same issue here.
Nextcloud 16.0.4 (de)
The plug-in seems to work in the backend.
Values are calculated and regularly updated/refreshed.
But the are not being shown.
I checked the progress bar with the inspector and this is the result:
![upload_progress_bar_error](https://user-images.githubusercontent.com/47253216/65394618-8f85b380-dd7f-11e9-82f6-e833554537c7.jpg)

**Comment by Excel1** [comment]
@burgha now it worked fo me on Firefox: 69.0 (64-bit) Arch Linux
